const SOURCE_PROJECT = ""
const SOURCE_DATASET = "analytics_383496534";
const REPORTING_TIME_ZONE = "Europe/Warsaw";
const REPORTS_DATASET = "ga4_reports";
const ATTRIBUTION_DATASET = "ga4_attribution";
const DATASET_BASIC = "ga4_basic";
const START_DATE = 20241125;
const START_DATE_TEST = 20241001;
const n_date = 3;
const SESSION_LOOKBACK_WINDOW = 7776000;

// zmienne dla GAds

const GADS_GET_DATA = true;
const GADS_SOURCE_PROJECT = "bigquery-411711";
const GADS_SOURCE_DATASET = "google_ads_raw";
const GADS_CUSTOMER_ID = "2155702465";


module.exports = {
    SOURCE_PROJECT,
    SOURCE_DATASET,
    REPORTING_TIME_ZONE,
    REPORTS_DATASET,
    ATTRIBUTION_DATASET,
    START_DATE,
    START_DATE_TEST,
    n_date,
    DATASET_BASIC,
    SESSION_LOOKBACK_WINDOW,
    GADS_GET_DATA,
    GADS_SOURCE_PROJECT,
    GADS_SOURCE_DATASET,
    GADS_CUSTOMER_ID

};
